# Generated by Django 5.1.4 on 2024-12-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_customuser_alter_rating_user_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('liked_actors', models.ManyToManyField(related_name='liked_by_users', to='project.actor')),
                ('liked_directors', models.ManyToManyField(related_name='liked_by_users', to='project.director')),
                ('rated_movies', models.ManyToManyField(related_name='rated_by', through='project.Rating', to='project.movie')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
