# Generated by Django 5.1.4 on 2024-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_user_alter_rating_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rated_movies',
            field=models.ManyToManyField(related_name='rated_by', to='project.rating'),
        ),
    ]
