# Generated by Django 5.1.4 on 2024-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_user_rated_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rated_movies',
            field=models.ManyToManyField(related_name='rated_by', through='project.Rating', to='project.movie'),
        ),
    ]
