# Generated by Django 5.1.4 on 2024-12-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='want_to_watch',
            field=models.BooleanField(default=False),
        ),
    ]
