# Generated by Django 5.1.4 on 2024-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_rating_want_to_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
