# Generated by Django 5.1.4 on 2024-12-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movies', to='project.director'),
        ),
    ]
