# Generated by Django 5.1.4 on 2024-12-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
